# permissions for end users to edit bgdeploymentoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bgdeploymentoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bg-deployment-operator
    app.kubernetes.io/part-of: bg-deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: bgdeploymentoperator-editor-role
rules:
- apiGroups:
  - bgdeploymentoperator.example.com
  resources:
  - bgdeploymentoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bgdeploymentoperator.example.com
  resources:
  - bgdeploymentoperators/status
  verbs:
  - get
