# permissions for end users to view bgdeploymentoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bgdeploymentoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bg-deployment-operator
    app.kubernetes.io/part-of: bg-deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: bgdeploymentoperator-viewer-role
rules:
- apiGroups:
  - bgdeploymentoperator.example.com
  resources:
  - bgdeploymentoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bgdeploymentoperator.example.com
  resources:
  - bgdeploymentoperators/status
  verbs:
  - get
